version: '3'

services:
  backend:
    build: ./backend
    container_name: flask-backend
    expose:
      - "5000"   # ya no se publica hacia afuera
    networks:
      - webnet

  frontend:
    build: ./frontend
    container_name: nginx-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - webnet

networks:
  webnet:
